export const MOVE_COMMAND_ENTERED = "MOVE_COMMAND_ENTERED";
export const TURN_COMMAND_ENTERED = "TURN_COMMAND_ENTERED";

export type Trigger = typeof MOVE_COMMAND_ENTERED | typeof TURN_COMMAND_ENTERED;
